apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "name" . }}-taskmanager
spec:
  replicas: {{ .Values.flink.num_taskmanagers }}
  selector:
    matchLabels:
      app: {{ template "name"  . }}
      component: taskmanager
  template:
    metadata:
      labels:
        app: {{ template "name"  . }}
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
#        resources:
#          limits:
#            cpu: {{ .Values.flink.num_slots_per_taskmanager }}
#            memory: {{ .Values.resources.taskmanager.limits.memory }}
#          requests:
#            cpu: {{ .Values.flink.num_slots_per_taskmanager }}
#            memory: {{ .Values.resources.taskmanager.requests.memory }}
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: nfs-volume
          mountPath: /opt/flink-stage
        securityContext:
          runAsUser: 9999 # refers to user _flink_ from official flink image, change if necessary  
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
            items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: log4j-console.properties
              path: log4j-console.properties
        - name: nfs-volume
          nfs: 
            server: {{ .Values.flink.storage.nfs_address }}
            path: /      