apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "name" . }}-jobmanager
spec:
  replicas: {{ .Values.flink.num_jobmanagers }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      component: jobmanager
  template:
    metadata:
      labels:
        app: {{ template "name"  . }}
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
#        resources:
#          limits:
#            cpu: {{ .Values.resources.jobmanager.limits.cpu }}
#            memory: {{ .Values.resources.jobmanager.limits.memory }}
#          requests:
#            cpu: {{ .Values.resources.jobmanager.requests.cpu }}
#            memory: {{ .Values.resources.jobmanager.requests.memory }}
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: nfs-volume
          mountPath: /opt/flink-stage
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
            items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: log4j-console.properties
              path: log4j-console.properties
        - name: nfs-volume
          nfs: 
            # URL for the NFS server
            server: {{ .Values.flink.storage.nfs_address }}
            path: /
