apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-jobmanager
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: {{ template "name"  . }}
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name"  . }}-jobmanager-rest
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: {{ template "name"  . }}
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name"  . }}-taskmanager-query-state
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: query-state
    port: 6125
    targetPort: 6125
    nodePort: 30025
  selector:
    app: {{ template "name"  . }}
    component: taskmanager    