apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: eve
spec:
  ports:
  - name: rpc
    port: 6123
    protocol: TCP
    targetPort: 6123
  - name: blob-server
    port: 6124
    protocol: TCP
    targetPort: 6124
  - name: webui
    port: 18081
    protocol: TCP
    targetPort: 18081
  selector:
    app: flink
    component: jobmanager
  sessionAffinity: None
  type: ClusterIP
