host_url: flink.local
image: flink
imageTag: scala_2.12-java11
imagePullPolicy: IfNotPresent
namespace: eve
resources:
  jobmanager:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 300m
      memory: 2Gi
  taskmanager:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 300m
      memory: 4Gi
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30

flink:
  jobmanager_memory_process_size: 3500m
  taskmanager_memory_process_size: 7500m
  num_jobmanagers: 1
  num_taskmanagers: 2
  num_slots_per_taskmanager: 2
  storage:
    nfs_address: 10.109.20.33
    high_availability_storageDir: file:///opt/flink-stage/recovery/
    jobmanager_archive_fs_dir: file:///opt/flink-stage/history/
    state_savepoints_dir: file:///opt/flink-stage/savepoint/
    web_upload_dir: /opt/flink-stage/data/jars/